export interface Service {
  id: string;
  name: string;
  icon: string;
  description: string;
  details: string[];
  price: string;
  priceUnit: string;
  rating: number;
  eta: string;
  color: string;
  popular: boolean;
}

export const allServices: Service[] = [
  { id: 'plumber', name: 'Plumber', icon: '🔧', description: 'Leak repair, tap fitting, blocked drains and bathroom plumbing.', details: ['Leak repair', 'Tap fitting', 'Drain cleaning'], price: '₹499', priceUnit: 'visit', rating: 4.8, eta: '30 min average dispatch', color: 'from-sky-500 to-blue-700', popular: true },
  { id: 'electrician', name: 'Electrician', icon: '⚡', description: 'Switchboards, fans, lights, wiring faults and new installations.', details: ['Fan fitting', 'Wiring faults', 'Switchboard repair'], price: '₹499', priceUnit: 'visit', rating: 4.9, eta: 'Fast home visit support', color: 'from-amber-400 to-orange-500', popular: true },
  { id: 'driver', name: 'Driver', icon: '🚗', description: 'Local trips, pickups, drops, hourly driving and event transport.', details: ['Hourly driver', 'Pickup/drop', 'Outstation support'], price: '₹399', priceUnit: 'hr', rating: 4.7, eta: 'Flexible hourly bookings', color: 'from-emerald-500 to-green-700', popular: false },
  { id: 'cleaner', name: 'Cleaner', icon: '🧹', description: 'Home, rental, office and deep cleaning visits with supplies support.', details: ['Home cleaning', 'Office cleaning', 'Deep cleaning'], price: '₹399', priceUnit: 'visit', rating: 4.8, eta: 'Routine or deep cleaning slots', color: 'from-cyan-500 to-teal-600', popular: true },
  { id: 'carpenter', name: 'Carpenter', icon: '🔨', description: 'Furniture fixes, wall mounts, shelves, handles and small fittings.', details: ['Furniture repair', 'Wall mounts', 'Shelf fitting'], price: '₹599', priceUnit: 'visit', rating: 4.7, eta: 'Furniture and fittings help', color: 'from-orange-500 to-amber-700', popular: false },
  { id: 'painter', name: 'Painter', icon: '🎨', description: 'Touch-ups, feature walls, seepage patching and room refresh work.', details: ['Wall touch-up', 'Room painting', 'Patch repair'], price: '₹699', priceUnit: 'visit', rating: 4.6, eta: 'Room refresh and touch-ups', color: 'from-rose-500 to-pink-700', popular: false },
  { id: 'mechanic', name: 'Mechanic', icon: '🛠️', description: 'Basic car and bike diagnosis, minor fixes and doorstep support.', details: ['Bike checkup', 'Car diagnosis', 'Minor fixes'], price: '₹499', priceUnit: 'visit', rating: 4.6, eta: 'Basic diagnosis support', color: 'from-slate-600 to-slate-800', popular: false },
  { id: 'gardener', name: 'Gardener', icon: '🌿', description: 'Pruning, watering, garden cleaning and seasonal plant upkeep.', details: ['Pruning', 'Garden cleanup', 'Plant care'], price: '₹399', priceUnit: 'visit', rating: 4.7, eta: 'Outdoor upkeep and trimming', color: 'from-lime-500 to-emerald-700', popular: false },
  { id: 'ac', name: 'AC Technician', icon: '❄️', description: 'AC repair, gas refill, installation, wet servicing and cooling checks.', details: ['Gas refill', 'Wet service', 'Installation'], price: '₹599', priceUnit: 'visit', rating: 4.9, eta: 'AC repair, refill and service visits', color: 'from-blue-400 to-cyan-700', popular: true },
  { id: 'tv', name: 'TV Repair', icon: '📺', description: 'LED, LCD and Smart TV repair, wall mounting and setup help.', details: ['Panel diagnosis', 'Wall mount', 'Smart TV setup'], price: '₹499', priceUnit: 'visit', rating: 4.6, eta: 'TV diagnosis and installation support', color: 'from-violet-500 to-indigo-700', popular: false },
  { id: 'laundry', name: 'Laundry', icon: '🧺', description: 'Washing, ironing, dry cleaning and pickup support for clothes.', details: ['Wash and fold', 'Ironing', 'Dry cleaning'], price: '₹299', priceUnit: 'order', rating: 4.7, eta: 'Washing, ironing and dry cleaning pickup', color: 'from-sky-400 to-teal-600', popular: false },
  { id: 'cook', name: 'Cook', icon: '🍳', description: 'Home cooking, daily meal prep, event cooking and kitchen help.', details: ['Daily meals', 'Event cooking', 'Meal prep'], price: '₹499', priceUnit: 'day', rating: 4.8, eta: 'Daily meals and event cooking help', color: 'from-red-500 to-orange-600', popular: true },
  { id: 'pet', name: 'Pet Care', icon: '🐶', description: 'Pet grooming, walking, feeding visits and basic care at home.', details: ['Pet walk', 'Grooming', 'Feeding visit'], price: '₹399', priceUnit: 'visit', rating: 4.7, eta: 'Grooming, walking and basic pet care', color: 'from-yellow-400 to-amber-600', popular: false },
  { id: 'locksmith', name: 'Locksmith', icon: '🔐', description: 'Door unlock, key duplication, lock repair and replacement.', details: ['Door unlock', 'Duplicate key', 'Lock repair'], price: '₹349', priceUnit: 'visit', rating: 4.6, eta: 'Unlocking, duplicate keys and lock repairs', color: 'from-zinc-500 to-stone-700', popular: false },
  { id: 'computer', name: 'Computer Repair', icon: '💻', description: 'Laptop, desktop, software, slow system and basic hardware issues.', details: ['Laptop repair', 'Software issue', 'PC tune-up'], price: '₹499', priceUnit: 'visit', rating: 4.7, eta: 'Laptop, PC and software issue support', color: 'from-blue-600 to-slate-800', popular: false },
  { id: 'wifi', name: 'WiFi Setup', icon: '📡', description: 'Router setup, password changes, coverage checks and internet fixes.', details: ['Router setup', 'Speed issue', 'Coverage check'], price: '₹299', priceUnit: 'visit', rating: 4.6, eta: 'Router setup and internet troubleshooting', color: 'from-indigo-500 to-blue-700', popular: false },
  { id: 'delivery', name: 'Delivery Helper', icon: '📦', description: 'Local parcel pickup, document drop and same-city delivery support.', details: ['Parcel pickup', 'Document drop', 'Local delivery'], price: '₹199', priceUnit: 'order', rating: 4.5, eta: 'Local pickup and parcel delivery support', color: 'from-orange-400 to-red-600', popular: false },
  { id: 'glass', name: 'Glass Repair', icon: '🪟', description: 'Window glass repair, replacement, sealing and small panel fixes.', details: ['Window repair', 'Glass replacement', 'Sealing'], price: '₹449', priceUnit: 'visit', rating: 4.5, eta: 'Window glass repair and replacement', color: 'from-cyan-300 to-blue-500', popular: false },
  { id: 'bathroom', name: 'Bathroom Cleaning', icon: '🚿', description: 'Deep bathroom cleaning, stain removal, scale removal and sanitization.', details: ['Deep cleaning', 'Scale removal', 'Sanitization'], price: '₹399', priceUnit: 'bathroom', rating: 4.8, eta: 'Deep cleaning and sanitization slots', color: 'from-teal-400 to-cyan-700', popular: false },
  { id: 'sofa', name: 'Sofa Cleaning', icon: '🛋️', description: 'Sofa shampooing, vacuuming, stain removal and fabric refresh.', details: ['Shampooing', 'Vacuuming', 'Stain removal'], price: '₹499', priceUnit: 'seat', rating: 4.7, eta: 'Sofa shampooing and stain removal', color: 'from-fuchsia-500 to-rose-700', popular: false },
  { id: 'kitchen', name: 'Kitchen Cleaning', icon: '🧼', description: 'Deep kitchen cleaning, oil removal, tiles, sink and chimney area cleanup.', details: ['Oil removal', 'Tile cleaning', 'Sink cleanup'], price: '₹599', priceUnit: 'kitchen', rating: 4.8, eta: 'Deep cleaning and oil removal visits', color: 'from-lime-500 to-green-700', popular: false },
  { id: 'inspection', name: 'Home Inspection', icon: '🏠', description: 'Basic maintenance inspection for plumbing, electrical and safety checks.', details: ['Plumbing check', 'Electrical check', 'Safety report'], price: '₹399', priceUnit: 'visit', rating: 4.6, eta: 'Basic home maintenance inspection', color: 'from-stone-500 to-neutral-700', popular: false },
  { id: 'inverter', name: 'Inverter Repair', icon: '🔋', description: 'Battery health checks, inverter repair, wiring and backup diagnosis.', details: ['Battery check', 'Backup issue', 'Wiring check'], price: '₹499', priceUnit: 'visit', rating: 4.6, eta: 'Battery and inverter repair support', color: 'from-green-500 to-emerald-800', popular: false },
  { id: 'tank', name: 'Water Tank Cleaning', icon: '🚰', description: 'Overhead and underground tank cleaning with hygiene treatment.', details: ['Tank wash', 'Sludge removal', 'Disinfection'], price: '₹599', priceUnit: 'tank', rating: 4.7, eta: 'Overhead tank cleaning and hygiene', color: 'from-sky-500 to-cyan-700', popular: false },
  { id: 'polish', name: 'Wood Polish', icon: '🪵', description: 'Furniture polishing, scratch touch-up and surface restoration.', details: ['Furniture polish', 'Scratch touch-up', 'Restoration'], price: '₹499', priceUnit: 'visit', rating: 4.6, eta: 'Furniture polishing and restoration', color: 'from-amber-700 to-yellow-600', popular: false },
  { id: 'appliance', name: 'Appliance Repair', icon: '🔧', description: 'Fridge, washing machine, mixer, microwave and small appliance repair.', details: ['Fridge repair', 'Washer repair', 'Mixer repair'], price: '₹499', priceUnit: 'visit', rating: 4.7, eta: 'Home appliance repair support', color: 'from-slate-500 to-blue-700', popular: false },
  { id: 'door', name: 'Door Repair', icon: '🚪', description: 'Door hinges, locks, handles, sliding channels and alignment repair.', details: ['Hinge repair', 'Handle repair', 'Sliding fix'], price: '₹399', priceUnit: 'visit', rating: 4.6, eta: 'Door hinges, locks and sliding repair', color: 'from-orange-700 to-stone-700', popular: false },
  { id: 'moving', name: 'Mover', icon: '🚚', description: 'House shifting, packing, loading, unloading and local moving help.', details: ['Packing', 'Loading', 'House shifting'], price: '₹999', priceUnit: 'job', rating: 4.8, eta: 'House shifting, packing and moving help', color: 'from-red-600 to-rose-800', popular: true },
  { id: 'pest', name: 'Pest Control', icon: '🛡️', description: 'Cockroach, ant, mosquito, termite and general pest treatment.', details: ['Cockroach control', 'Termite check', 'General spray'], price: '₹799', priceUnit: 'visit', rating: 4.7, eta: 'Same-day pest treatment slots', color: 'from-emerald-600 to-lime-700', popular: true },
  { id: 'cctv', name: 'CCTV Setup', icon: '📹', description: 'Camera installation, DVR setup, mobile viewing and troubleshooting.', details: ['Camera install', 'DVR setup', 'Mobile view'], price: '₹699', priceUnit: 'camera', rating: 4.6, eta: 'Security camera setup support', color: 'from-slate-700 to-indigo-800', popular: false },
  { id: 'salon', name: 'Salon at Home', icon: '💇', description: 'Haircut, grooming, facial, waxing and home salon appointments.', details: ['Haircut', 'Facial', 'Grooming'], price: '₹399', priceUnit: 'session', rating: 4.8, eta: 'At-home salon appointments', color: 'from-pink-500 to-rose-700', popular: true },
  { id: 'babysitter', name: 'Babysitter', icon: '🍼', description: 'Short-duration child care support for home, events and errands.', details: ['Child care', 'Event support', 'Hourly help'], price: '₹249', priceUnit: 'hr', rating: 4.6, eta: 'Hourly child care support', color: 'from-purple-500 to-pink-600', popular: false },
  { id: 'eldercare', name: 'Elder Care', icon: '🩺', description: 'Companion visits, medicine reminders and basic non-medical support.', details: ['Companion visit', 'Medicine reminder', 'Basic support'], price: '₹299', priceUnit: 'hr', rating: 4.7, eta: 'Respectful home care visits', color: 'from-teal-500 to-emerald-700', popular: false },
  { id: 'nurse', name: 'Nurse Visit', icon: '💉', description: 'Injection support, vitals check and basic home nursing visit.', details: ['Vitals check', 'Injection support', 'Dressing help'], price: '₹599', priceUnit: 'visit', rating: 4.8, eta: 'Home nursing visit support', color: 'from-red-500 to-pink-700', popular: false },
  { id: 'tutor', name: 'Tutor', icon: '📚', description: 'Home tutoring for school subjects, homework and exam practice.', details: ['Homework help', 'Exam practice', 'Subject tuition'], price: '₹299', priceUnit: 'hr', rating: 4.7, eta: 'Hourly learning sessions', color: 'from-blue-500 to-violet-700', popular: false },
  { id: 'carwash', name: 'Car Wash', icon: '🚘', description: 'Exterior wash, interior vacuum, polish and doorstep car cleaning.', details: ['Exterior wash', 'Interior vacuum', 'Polish'], price: '₹349', priceUnit: 'car', rating: 4.6, eta: 'Doorstep car cleaning slots', color: 'from-cyan-500 to-sky-700', popular: false },
  { id: 'chimney', name: 'Chimney Cleaning', icon: '🔥', description: 'Kitchen chimney filter cleaning, oil removal and suction check.', details: ['Filter cleaning', 'Oil removal', 'Suction check'], price: '₹499', priceUnit: 'chimney', rating: 4.6, eta: 'Kitchen chimney cleaning visits', color: 'from-orange-600 to-red-700', popular: false },
  { id: 'waterpurifier', name: 'Water Purifier', icon: '💧', description: 'RO service, filter change, leakage repair and water taste checks.', details: ['RO service', 'Filter change', 'Leak repair'], price: '₹449', priceUnit: 'visit', rating: 4.7, eta: 'RO and purifier service support', color: 'from-blue-500 to-cyan-700', popular: false },
];

export const servicesById = allServices.reduce<Record<string, Service>>((services, service) => {
  services[service.id] = service;
  return services;
}, {});
